name: c.gl
favicon: null
layout_spectrum: 1
typography_spectrum: 0.18758
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e1d23'
    - '#797067'
    - '#41454e'
    - '#e3e3d7'
    - '#9c9680'
  brandStrength: 0.375
  lightness: 0.6771166538819671
  saturation: 0.894396506017074
  rhythmicContrast: 0.4489062207285315
purpose: []
